export const dummyInput = {'target': '',
'no': "0",
'contents': [{'question': "初回APIがうまく動かない問題。。。画面が真っ白になったらリロードお願いします。。。\n2024/01/18更新・・・７問回答後の結果表示ページ追加",
  'option': [],
  'answer': [],
  'explanation': ''},
  {'question': "問題が選択されていません",
  'option': [],
  'answer': [],
  'explanation': ''},
  {'question': "問題が選択されていません",
  'option': [],
  'answer': [],
  'explanation': ''},
  {'question': "問題が選択されていません",
  'option': [],
  'answer': [],
  'explanation': ''},
  {'question': "問題が選択されていません",
  'option': [],
  'answer': [],
  'explanation': ''},
  {'question': "問題が選択されていません",
  'option': [],
  'answer': [],
  'explanation': ''},
  {'question': "問題が選択されていません",
  'option': [],
  'answer': [],
  'explanation': ''},
 ]}