export const dummyInput = {'target': '',
'no': "0",
'contents': [{'question': "問題が選択されていません",
  'option': [],
  'answer': [],
  'explanation': ''},
  {'question': "問題が選択されていません",
  'option': [],
  'answer': [],
  'explanation': ''},
  {'question': "問題が選択されていません",
  'option': [],
  'answer': [],
  'explanation': ''},
  {'question': "問題が選択されていません",
  'option': [],
  'answer': [],
  'explanation': ''},
  {'question': "問題が選択されていません",
  'option': [],
  'answer': [],
  'explanation': ''},
  {'question': "問題が選択されていません",
  'option': [],
  'answer': [],
  'explanation': ''},
  {'question': "問題が選択されていません",
  'option': [],
  'answer': [],
  'explanation': ''},
 ]}